# Generated by Django 3.1.6 on 2021-04-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('interact', '0002_auto_20210421_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ref_id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='ref_id',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='ref_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_parent',
            field=models.ForeignKey(db_column='post_parent', default='cc', on_delete=django.db.models.deletion.CASCADE, to='post.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='post_parent',
            field=models.ForeignKey(db_column='post_parent', default='cc', on_delete=django.db.models.deletion.CASCADE, to='post.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='comment_parent',
            field=models.ForeignKey(db_column='comment_parent', default='cc', on_delete=django.db.models.deletion.CASCADE, to='interact.comment'),
            preserve_default=False,
        ),
    ]
