# Generated by Django 3.1.6 on 2021-04-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0003_auto_20210421_2311'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('owner', 'post_parent'), name='unique_like'),
        ),
    ]
