# Generated by Django 3.1.6 on 2021-04-25 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210425_1648'),
        ('interact', '0006_auto_20210425_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_parent',
            field=models.ForeignKey(db_column='post_parent', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='post.post'),
        ),
    ]
