# Generated by Django 3.1.6 on 2021-05-02 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0007_auto_20210425_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_comment', to='interact.comment'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
