# Generated by Django 3.1.6 on 2021-06-19 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210425_1648'),
        ('interact', '0008_auto_20210502_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='latest_reply_ids_string',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_parent',
            field=models.ForeignKey(db_column='post_parent', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='like',
            name='post_parent',
            field=models.ForeignKey(db_column='post_parent', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.post'),
        ),
    ]
